CREATE DATABASE estacionamento;
USE estacionamento;

CREATE TABLE Marcas_Carro(
    ID_MARCA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_MARCAR VARCHAR(15)
);

CREATE TABLE Tipos_Pagamento(
    ID_TIPO_PAGTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_TIPO_PAGTO VARCHAR(15)
);

CREATE TABLE Cliente(
    CPF INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(20),
    EMAIL VARCHAR(50),
    TELEFONE VARCHAR(14),
    CNH VARCHAR(20),
    DT_NASCTO DATE
);

CREATE TABLE Cartao_Caucao(
    ID_CARTAO INT NOT NULL PRIMARY KEY,
    NOME_CARTAO VARCHAR(30),
    NUMERO_CARTAO INT,
    DT_VENCTO_CARTAO DATE,
    CVC_CARTAO INT,
    CLIENTE INT,
    FOREIGN KEY (CLIENTE) REFERENCES Cliente(CPF)
);

CREATE TABLE Carro(
    PLACA VARCHAR(10) NOT NULL PRIMARY KEY,
    MARCA INT,
    KM INT,
    ANO INT,
    COR VARCHAR(10),
    DESCRICAO VARCHAR(255),
    MODELO VARCHAR(50),
    VALOR DECIMAL(8,2) NOT NULL,
    FOREIGN KEY (MARCA) REFERENCES Marcas_Carro(ID_MARCA)
);

CREATE TABLE VENDA(
    ID_NOTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DT_VENDA DATE,
    CARRO_VENDA VARCHAR(10),
    CLIENTE_VENDA INT,
    TIPO_PAGTO_VENDA INT,
    VALOR_VENDA DECIMAL(8,2),
    FOREIGN KEY (CARRO_VENDA) REFERENCES Carro(PLACA),
    FOREIGN KEY (CLIENTE_VENDA) REFERENCES Cliente(CPF),
    FOREIGN KEY (TIPO_PAGTO_VENDA) REFERENCES Tipos_Pagamento(ID_TIPO_PAGTO)
);