CREATE DATABASE HAMBURGUERIA;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    TELEFONE INT UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    ENDERECO VARCHAR(100)
);

CREATE TABLE TIPO_DO_PRODUTO(
    ID_TIPO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100) NOT NULL 
);

CREATE TABLE FORNECEDOR(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) UNIQUE NOT NULL ,
    TELEFONE INT UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CNPJ INT UNIQUE NOT NULL
);

CREATE TABLE STATUS_DO_PEDIDO(
    ID_STATUS INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR (30) NOT NULL,
    PRIORIDADE VARCHAR (30)
);

CREATE TABLE FORMA_DE_PAGAMENTO(
    ID_FORMA_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(30) NOT NULL,
    TAXA DECIMAL(7,2) not null
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(7,2) NOT NULL,
    ID_TIPO INT,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_DO_PRODUTO(ID_TIPO),
    DISPONIBILIDADE CHAR(1) NOT NULL,
    IMAGEM_URL VARCHAR(255)
);

CREATE TABLE PEDIDO(
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    DATAA DATE NOT NULL,
    ID_CLIENTE INT,
    ID_FORMA_PAGAMENTO INT,
    ID_STATUS INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    TOTAL DECIMAL(7,2) NOT NULL,
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES FORMA_DE_PAGAMENTO(ID_FORMA_PAGAMENTO),
    FOREIGN KEY (ID_STATUS) REFERENCES STATUS_DO_PEDIDO(ID_STATUS)
);

CREATE TABLE ITEM_DO_PRODUTO(
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_PEDIDO INT,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    ID_PRODUTO INT,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    QUANTIDADE INT NOT NULL, 
    SUBTOTAL DECIMAL(7,2) NOT NULL
);
