create table TIPOS_ARMADURA(
    ID int AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(10)
);

CREATE TABLES CONSUMIVEIS(
    ID AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(32),
    QUANTIDADE INT
);

CREATE TABLE CLASSES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30),
    VITALIDADE INT,
    MENTE INT,
    TENACIDADE INT,
    FORCA INT,
    DESTREZA INT,
    INTELIGENCIA INT,
    FE INT,
    ARCANO INT
);

CREATE TABLE TIPO_ATAQUE(
    ID AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(25)
);

CREATE TABLE ORIGEM(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FONTE VARCHAR(20)
);


FOREIGN KEY (id_tabela_referenciada) REFERENCES tabela_referenciada(id)
